name: build librespot package for debian bookworm and trixie

on:
  pull_request:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64, armhf, arm64]
        debian: [bookworm, trixie]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: librespot-org/librespot
          ref: v0.7.0
          path: librespot
      - name: Build rust binary
        uses: catango/build-rust-deb-action@master
        id: build
        with:
          host-build-deps: libclang-dev cmake git
          target-build-deps: libpulse-dev libasound2-dev libssl-dev
          target-arch: ${{ matrix.architecture }}
          rust-features: pulseaudio-backend
          rust-version: 1.89.0
          source-dir: librespot
          docker-image: debian:${{ matrix.debian }}-slim
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: librespot_0.7.0-${{ matrix.debian }}_${{ matrix.architecture }}
          path: ${{ steps.build.outputs.artifact-dir }}


  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Zip artifacts for archiving
        run: for i in */; do zip -r "${i%/}.zip" "$i"; done
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: librespot*.zip
          tag_name: ${{ github.ref_name }}
          body: "Automated release of ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
